### ISSUE TITLE
Issues with sourcemaps while debugging

### ISSUE THREAD

**Issue by wrygiel** [piecioshka/boilerplate-karma-typescript#1]
Hi there! Thank you for sharing this template.

I'm trying to modify your setup to support debugging sessions in Chrome, and I'm wondering why it doesn't work for me. Given there were no recent commits here, I suspect you no longer use it - feel free to ignore my inquiry if that's the case.

1. I added a simple `debugger` statement to your example:

   ![image](https://user-images.githubusercontent.com/2168535/207980285-9d57dd45-01e8-441e-b923-09aef9872a67.png)

1. `npm run test:watch` successfully launches Karma at http://localhost:9876/, and when I open it in my browser, the execution stops at the `debugger` statement as expected.

1. However, for some reason I cannot understand, Chrome fails to recognize sourcemaps in *some* of the served files:

   - The file with the `debugger` statement (doesn't work):

     ![image](https://user-images.githubusercontent.com/2168535/207980772-94403ed1-f3b8-46f3-a8e6-eac2fda13a00.png)

   - The spec file, one level higher in the stack trace (works):

     ![image](https://user-images.githubusercontent.com/2168535/207980928-9ba996d2-b7b1-44e1-ad50-a3d527735f61.png)

I spent a couple of hours trying to find a solution for this already, with no luck. If you happen to know anything which could help me, it would be awesome!

**Comment by piecioshka** [comment]
I'm sorry, but I cannot resolve this issue.
